version: "3.8"

services:
  app:
    image: auliahanifh/devops-pso:laravel-app
    ports:
      - "80:80"
      - "443:443"
    # environment:
    #   DB_HOST: ${DB_HOST}
    #   DB_USERNAME: ${DB_USERNAME}
    #   DB_PASSWORD: ${DB_PASSWORD}
    #   DB_DATABASE: ${DB_DATABASE}
    env_file:
      - .env
    depends_on:
      - mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - appnet

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: devops-pso321
      MYSQL_DATABASE: trial_laravel
    volumes:
      - db_data:/var/lib/mysql
      # - ./trial_laravel.sql:/docker-entrypoint-initdb.d/trial_laravel.sql:ro
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-pdevops-pso321"]
      interval: 10s
      timeout: 5s
      retries: 3
#      start_period: 60s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
    driver: overlay