  
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://206.189.40.123:9090
    basicAuth: false
    isDefault: true
    editable: true
